#!/bin/bash

echo "=================================="
echo "Audio.TUI - Audio Setup Complete!"
echo "=================================="
echo ""
echo "✓ BlackHole 2ch has been installed"
echo ""
echo "IMPORTANT: You need to configure your audio output"
echo ""
echo "Option 1: Automatic Setup (Recommended)"
echo "========================================="
echo "Run this command to create a Multi-Output Device:"
echo ""
echo "osascript -e 'tell application \"Audio MIDI Setup\" to activate'"
echo ""
echo "Then in Audio MIDI Setup:"
echo "1. Click the '+' button (bottom left)"
echo "2. Select 'Create Multi-Output Device'"
echo "3. Check BOTH boxes:"
echo "   ☑ Your current output (e.g., 'MacBook Pro Speakers')"
echo "   ☑ BlackHole 2ch"
echo "4. Right-click the Multi-Output Device"
echo "5. Select 'Use This Device For Sound Output'"
echo ""
echo "Option 2: Use BlackHole Directly (No sound from speakers)"
echo "==========================================================="
echo "Go to System Settings > Sound > Output"
echo "Select 'BlackHole 2ch'"
echo "(You won't hear audio, but visualizer will work)"
echo ""
echo "After setup, in Audio.TUI:"
echo "- Press 'm' to switch to System Audio mode"
echo "- Press 'i' to select 'BlackHole 2ch' as input"
echo "- Press ']' several times to increase sensitivity"
echo "- Play music from Spotify, YouTube, etc!"
echo ""
read -p "Press Enter to open Audio MIDI Setup..."
open "/System/Applications/Utilities/Audio MIDI Setup.app"
echo ""
echo "Setup complete! Restart Audio.TUI to use the new features."
