#!/bin/bash

echo "=========================================="
echo "Audio.TUI - Speaker Audio Capture Setup"
echo "=========================================="
echo ""
echo "IMPORTANT: To visualize what's playing from your SPEAKERS,"
echo "you need to route your speaker output through BlackHole."
echo ""
echo "This requires creating a Multi-Output Device."
echo ""
echo "Opening Audio MIDI Setup now..."
echo ""
sleep 2

# Open Audio MIDI Setup
open "/System/Applications/Utilities/Audio MIDI Setup.app"

echo "Follow these steps IN AUDIO MIDI SETUP:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Create Multi-Output Device"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Click the '+' button at the BOTTOM LEFT"
echo "2. Select 'Create Multi-Output Device'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Configure the Device"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Check BOTH boxes (very important!):"
echo "   ☑ Your speakers (e.g., 'MacBook Pro Speakers')"
echo "   ☑ BlackHole 2ch"
echo ""
echo "This sends audio to BOTH your speakers AND BlackHole"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Set as System Output"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option A (In Audio MIDI Setup):"
echo "  - Right-click 'Multi-Output Device'"
echo "  - Select 'Use This Device For Sound Output'"
echo ""
echo "Option B (In System Settings):"
echo "  - Go to System Settings > Sound > Output"
echo "  - Select 'Multi-Output Device'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Test It"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Play music from Spotify/YouTube"
echo "2. You should HEAR the audio from your speakers"
echo "3. In Audio.TUI:"
echo "   - Press 'm' to switch to System Audio mode"
echo "   - Press 'i' until you see 'BlackHole 2ch'"
echo "   - Press ']' 10-15 times to increase sensitivity"
echo "   - The visualizer should react to your music!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "WHY THIS WORKS:"
echo "• Multi-Output Device = Audio goes to speakers + BlackHole"
echo "• You hear audio from speakers"
echo "• Audio.TUI captures from BlackHole input"
echo "• Result: Visualize what you hear!"
echo ""
read -p "Press Enter after you've completed the setup..."

echo ""
echo "✓ Setup complete!"
echo ""
echo "Now in Audio.TUI:"
echo "1. Press 'm' - Switch to System Audio mode"
echo "2. Press 'i' - Select 'BlackHole 2ch' (NOT microphone!)"
echo "3. Press ']' - Increase sensitivity (10-15 times)"
echo "4. Play music - visualizer should work!"
echo ""
echo "If BlackHole 2ch doesn't appear when pressing 'i':"
echo "• Make sure you created the Multi-Output Device"
echo "• Make sure you set it as system output"
echo "• Restart Audio.TUI"
